# Assignment 5
### Name : Priyanka Bagave
### Roll No : 31208
### Batch : K2

1. Implement	logistic	regression	using	Python/R	to	perform	classification	on Social_Network_Ads.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision,Recall on the given dataset.

In [67]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline

In [68]:
df=pd.read_csv('Social_Network_Ads.csv')

In [69]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [70]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [71]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [72]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [73]:
df.shape

(400, 5)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [75]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [76]:
df.isnull()

User ID  Gender    Age  EstimatedSalary  Purchased
0      False   False  False            False      False
1      False   False  False            False      False
2      False   False  False            False      False
3      False   False  False            False      False
4      False   False  False            False      False
..       ...     ...    ...              ...        ...
395    False   False  False            False      False
396    False   False  False            False      False
397    False   False  False            False      False
398    False   False  False            False      False
399    False   False  False            False      False

[400 rows x 5 columns]

In [77]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [78]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

In [79]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
X = df[['Gender','Age','EstimatedSalary']]
y = df['Purchased']
print(X,y)

     Gender  Age  EstimatedSalary
0         1   19            19000
1         1   35            20000
2         0   26            43000
3         0   27            57000
4         1   19            76000
..      ...  ...              ...
395       0   46            41000
396       1   51            23000
397       0   50            20000
398       1   36            33000
399       0   49            36000

[400 rows x 3 columns] 0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64


In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
print(X_train, X_test,y_train,y_test)

     Gender  Age  EstimatedSalary
336       1   58           144000
64        0   59            83000
55        0   24            55000
106       0   26            35000
300       0   58            38000
..      ...  ...              ...
323       0   48            30000
192       1   29            43000
117       1   36            52000
47        0   27            54000
172       0   26           118000

[320 rows x 3 columns]      Gender  Age  EstimatedSalary
132       1   30            87000
309       0   38            50000
341       1   35            75000
196       0   30            79000
246       0   35            50000
..      ...  ...              ...
14        1   18            82000
363       0   42            79000
304       0   40            60000
361       0   53            34000
329       0   47           107000

[80 rows x 3 columns] 336    1
64     0
55     0
106    0
300    1
      ..
323    1
192    0
117    0
47     0
172    0
Name: Purchased, Length: 320, dtype: i

In [83]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [84]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0,solver="lbfgs")
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print(X_test)

[[ 1.02532046e+00 -7.98950822e-01  4.94607583e-01]
 [-9.75304830e-01 -2.12648508e-02 -5.77359062e-01]
 [ 1.02532046e+00 -3.12897090e-01  1.46942725e-01]
 [-9.75304830e-01 -7.98950822e-01  2.62831011e-01]
 [-9.75304830e-01 -3.12897090e-01 -5.77359062e-01]
 [ 1.02532046e+00 -1.09058306e+00 -1.44652121e+00]
 [-9.75304830e-01 -7.01740076e-01 -1.59138156e+00]
 [ 1.02532046e+00 -2.15686344e-01  2.14601566e+00]
 [-9.75304830e-01 -1.96547978e+00 -5.58617754e-02]
 [ 1.02532046e+00  8.53631867e-01 -7.80163563e-01]
 [ 1.02532046e+00 -7.98950822e-01 -6.06331134e-01]
 [-9.75304830e-01 -9.93372315e-01 -4.32498705e-01]
 [ 1.02532046e+00 -1.18475597e-01 -4.32498705e-01]
 [ 1.02532046e+00  7.59458956e-02  2.04886868e-01]
 [ 1.02532046e+00 -1.77105829e+00  4.65635512e-01]
 [-9.75304830e-01 -6.04529329e-01  1.36376973e+00]
 [ 1.02532046e+00 -1.18475597e-01  2.04886868e-01]
 [ 1.02532046e+00 -1.86826903e+00  4.36663440e-01]
 [-9.75304830e-01  1.63131784e+00  1.74040666e+00]
 [ 1.02532046e+00 -3.12897090e-

In [85]:
print(y_pred[:20])

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0]


In [86]:
print(y_test[:20])

132    0
309    0
341    0
196    0
246    0
60     0
155    0
261    1
141    0
214    0
37     0
134    0
113    0
348    0
12     0
59     0
293    0
140    0
206    1
199    0
Name: Purchased, dtype: int64


# Confusion Matrix

In [87]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print("Accuracy Score : ",accuracy_score(y_test,y_pred))
cm

Accuracy Score :  0.9125


array([[56,  2],
       [ 5, 17]], dtype=int64)

# True Positive

In [88]:
tp = cm[0,0]
tn = cm[1,1]
fp = cm[1,0]
fn = cm[0,1]
print("True Positive : ", tp)
print("True Negative : ", tn)
print("False Positive : ", fp)
print("False Negative : ", fn)

True Positive :  56
True Negative :  17
False Positive :  5
False Negative :  2


# Accuracy

In [89]:
acc = (tp+tn)/(tp+tn+fp+fn)
print("Accuracy Score", acc)

Accuracy Score 0.9125


# Error Rate

In [90]:
e = (fp+fn)/(tp+tn+fp+fn)
print("Error rate : ",e)

Error rate :  0.0875


# Precision

In [91]:
p_0 = tp/(tp+fp)
print("Precision for 0 : ", p_0)
p_1 = tn/(tn+fn)
print("Precision for 1 : ", p_1)

Precision for 0 :  0.9180327868852459
Precision for 1 :  0.8947368421052632


# Recall

In [92]:
r_0 = tp/(tp+fn)
print("Recall for 0 : ", r_0)
r_1 = tn/(tn+fp)
print("Recall for 1 : ",r_1)

Recall for 0 :  0.9655172413793104
Recall for 1 :  0.7727272727272727


In [93]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94        58
           1       0.89      0.77      0.83        22

    accuracy                           0.91        80
   macro avg       0.91      0.87      0.89        80
weighted avg       0.91      0.91      0.91        80

